# Site Info
title:              Josh Javier
description:        A personal blog on writing, coding, and being fearless
author_name:        Josh Javier
logo_url:           https://avatars0.githubusercontent.com/u/46987872?v=4 # Get it from GitHub API: https://api.github.com/users/<username>

# Site Settings
url:                https://joshjavier.github.io
baseurl:            ""
permalink:          pretty
timezone:           Asia/Manila
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-sitemap
  - jekyll-remote-theme

remote_theme: heiswayi/the-plain

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
